import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import PostCard from "../components/Posts/PostCard";
import categoryProvider from "../helper/category-provider";
import CategoryCard from "../components/CategoryCards/CategoryCard";
import NewsletterForm from "../components/NewsletterForm/NewsletterForm";
import { useRouter } from "next/router";
import { getMostPopularReads } from "../helper/API/utilities";

export default function Home(props) {
  const router = useRouter();

  function allPostsClickHandler() {
    router.push("/posts");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Travel Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="hero" className={styles.hero}>
        <div className={styles.container}>
          <Image
            priority={true}
            src="/banner2.jpg"
            alt="travel"
            width={1500}
            height={750}
          />
          <span />
          <div className={styles.intro}>
            <Image src="/image.jpg" alt="my-photo" width={400} height={400} />
            <div>
              <h2>Hi! I am Dan</h2>
              <p>
                A solo traveller and explorer. I am a freelance photographer and
                videographer working remotely from different parts of world as I
                travel.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section
        className={`${styles["responsive-container"]} ${styles.popular}`}
      >
        <h3>Most Popular Reads</h3>
        <div className={styles["post-card-container"]}>
          {props.data.map((post) => (
            <PostCard key={post.postId} postData={post} />
          ))}
        </div>
      </section>

      <section
        className={`${styles.category} ${styles["responsive-container"]}`}
      >
        <h3 style={{ marginBottom: "2.5em" }}>Read by Category</h3>
        <div className={styles["category-card-container"]}>
          <CategoryCard catDetails={categoryProvider[0]} />
          <CategoryCard catDetails={categoryProvider[1]} flexReverse />
          <CategoryCard catDetails={categoryProvider[2]} />
        </div>
        <button
          onClick={allPostsClickHandler}
          className={styles["all-posts-btn"]}
        >
          Show All Posts
        </button>
      </section>

      <section
        className={`${styles["responsive-container"]} ${styles.newsletter}`}
      >
        <Image
          src="/newsletter.jpg"
          alt="Newsletter image"
          height={300}
          width={600}
        />
        <NewsletterForm />
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const data = await getMostPopularReads();

  return {
    props: {
      data,
    },
  };
}
